require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CeosController do

  # This should return the minimal set of attributes required to create a valid
  # Ceo. As you add validations to Ceo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ceos as @ceos" do
      ceo = Ceo.create! valid_attributes
      get :index
      assigns(:ceos).should eq([ceo])
    end
  end

  describe "GET show" do
    it "assigns the requested ceo as @ceo" do
      ceo = Ceo.create! valid_attributes
      get :show, :id => ceo.id.to_s
      assigns(:ceo).should eq(ceo)
    end
  end

  describe "GET new" do
    it "assigns a new ceo as @ceo" do
      get :new
      assigns(:ceo).should be_a_new(Ceo)
    end
  end

  describe "GET edit" do
    it "assigns the requested ceo as @ceo" do
      ceo = Ceo.create! valid_attributes
      get :edit, :id => ceo.id.to_s
      assigns(:ceo).should eq(ceo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ceo" do
        expect {
          post :create, :ceo => valid_attributes
        }.to change(Ceo, :count).by(1)
      end

      it "assigns a newly created ceo as @ceo" do
        post :create, :ceo => valid_attributes
        assigns(:ceo).should be_a(Ceo)
        assigns(:ceo).should be_persisted
      end

      it "redirects to the created ceo" do
        post :create, :ceo => valid_attributes
        response.should redirect_to(Ceo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ceo as @ceo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ceo.any_instance.stub(:save).and_return(false)
        post :create, :ceo => {}
        assigns(:ceo).should be_a_new(Ceo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ceo.any_instance.stub(:save).and_return(false)
        post :create, :ceo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ceo" do
        ceo = Ceo.create! valid_attributes
        # Assuming there are no other ceos in the database, this
        # specifies that the Ceo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ceo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ceo.id, :ceo => {'these' => 'params'}
      end

      it "assigns the requested ceo as @ceo" do
        ceo = Ceo.create! valid_attributes
        put :update, :id => ceo.id, :ceo => valid_attributes
        assigns(:ceo).should eq(ceo)
      end

      it "redirects to the ceo" do
        ceo = Ceo.create! valid_attributes
        put :update, :id => ceo.id, :ceo => valid_attributes
        response.should redirect_to(ceo)
      end
    end

    describe "with invalid params" do
      it "assigns the ceo as @ceo" do
        ceo = Ceo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ceo.any_instance.stub(:save).and_return(false)
        put :update, :id => ceo.id.to_s, :ceo => {}
        assigns(:ceo).should eq(ceo)
      end

      it "re-renders the 'edit' template" do
        ceo = Ceo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ceo.any_instance.stub(:save).and_return(false)
        put :update, :id => ceo.id.to_s, :ceo => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ceo" do
      ceo = Ceo.create! valid_attributes
      expect {
        delete :destroy, :id => ceo.id.to_s
      }.to change(Ceo, :count).by(-1)
    end

    it "redirects to the ceos list" do
      ceo = Ceo.create! valid_attributes
      delete :destroy, :id => ceo.id.to_s
      response.should redirect_to(ceos_url)
    end
  end

end
