require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncomesController do

  # This should return the minimal set of attributes required to create a valid
  # Income. As you add validations to Income, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all incomes as @incomes" do
      income = Income.create! valid_attributes
      get :index
      assigns(:incomes).should eq([income])
    end
  end

  describe "GET show" do
    it "assigns the requested income as @income" do
      income = Income.create! valid_attributes
      get :show, :id => income.id.to_s
      assigns(:income).should eq(income)
    end
  end

  describe "GET new" do
    it "assigns a new income as @income" do
      get :new
      assigns(:income).should be_a_new(Income)
    end
  end

  describe "GET edit" do
    it "assigns the requested income as @income" do
      income = Income.create! valid_attributes
      get :edit, :id => income.id.to_s
      assigns(:income).should eq(income)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Income" do
        expect {
          post :create, :income => valid_attributes
        }.to change(Income, :count).by(1)
      end

      it "assigns a newly created income as @income" do
        post :create, :income => valid_attributes
        assigns(:income).should be_a(Income)
        assigns(:income).should be_persisted
      end

      it "redirects to the created income" do
        post :create, :income => valid_attributes
        response.should redirect_to(Income.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved income as @income" do
        # Trigger the behavior that occurs when invalid params are submitted
        Income.any_instance.stub(:save).and_return(false)
        post :create, :income => {}
        assigns(:income).should be_a_new(Income)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Income.any_instance.stub(:save).and_return(false)
        post :create, :income => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested income" do
        income = Income.create! valid_attributes
        # Assuming there are no other incomes in the database, this
        # specifies that the Income created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Income.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => income.id, :income => {'these' => 'params'}
      end

      it "assigns the requested income as @income" do
        income = Income.create! valid_attributes
        put :update, :id => income.id, :income => valid_attributes
        assigns(:income).should eq(income)
      end

      it "redirects to the income" do
        income = Income.create! valid_attributes
        put :update, :id => income.id, :income => valid_attributes
        response.should redirect_to(income)
      end
    end

    describe "with invalid params" do
      it "assigns the income as @income" do
        income = Income.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Income.any_instance.stub(:save).and_return(false)
        put :update, :id => income.id.to_s, :income => {}
        assigns(:income).should eq(income)
      end

      it "re-renders the 'edit' template" do
        income = Income.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Income.any_instance.stub(:save).and_return(false)
        put :update, :id => income.id.to_s, :income => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested income" do
      income = Income.create! valid_attributes
      expect {
        delete :destroy, :id => income.id.to_s
      }.to change(Income, :count).by(-1)
    end

    it "redirects to the incomes list" do
      income = Income.create! valid_attributes
      delete :destroy, :id => income.id.to_s
      response.should redirect_to(incomes_url)
    end
  end

end
